version: "3"

services:
  app:
    image: traefik:latest
    env_file: /share/appdata/config/traefik/traefik.env
    ports:
      - 80:80
      - 443:443
#      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /share/appdata/config/traefik:/etc/traefik
    networks:
      - traefik_public
    command: --api --docker --docker.swarmmode --docker.watch --docker.domain=<yourdomainhere>
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.frontend.rule=Host:traefik.<yourdomainhere>
        - traefik.enable=true
        - traefik.docker.network=traefik_public
        - traefik.port=8080
        - "traefik.frontend.auth.forward.address=http://<swarmIPhere>:8080/authorize"
        - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"
    logging:
      driver: gelf
      options:
         gelf-address: udp://<swarmIPhere>:12201
         labels: traefik

  whoami:
    image: containous/whoami
    networks:
      - traefik_public
    deploy:
      labels:
        - "traefik.frontend.rule=Host:whoami.<yourdomainhere>"
        - "traefik.enable=true"
        - traefik.docker.network=traefik_public
        - "traefik.port=80"
        - "traefik.frontend.auth.forward.address=http://<swarmIPhere>:8080/authorize"
        - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"

  auth:
    image: dniel/forwardauth
    networks:
      - traefik_public
    ports:
      - 8080:8080
    deploy:
      labels:
        - traefik.frontend.rule=Host:auth.<yourdomainhere>
        - traefik.enable=true
        - traefik.docker.network=traefik_public
        - traefik.port=8080
    volumes:
      - /share/appdata/config/traefik/application.yaml:/config/application.yaml

  www:
    image: dniel/blogr-www
    networks:
      - traefik_public
    deploy:
      labels:
        - "traefik.frontend.rule=Host:www.<yourdomainhere>"
        - "traefik.enable=true"
        - "traefik.port=80"
        - traefik.docker.network=traefik_public
        - "traefik.frontend.auth.forward.address=http://<swarmIPhere>:8080/authorize"
        - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"

networks:
  traefik_public:
    external: true
