#Substitute this container for the forward-auth in original traefik.yml

  traefik-forward-auth:
    image: funkypenguin/traefik-forward-auth
    env_file: /share/appdata/config/traefik/traefik-forward-auth.env
    networks:
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.auth.entrypoints=https"
        - "traefik.http.routers.auth.rule=Host(`auth.gkoerk.com`)"
        - "traefik.http.routers.auth.tls.certresolver=cloudflare"
        - "traefik.http.routers.auth.middlewares=forward-auth@file"
        - "traefik.http.services.auth.loadbalancer.server.port=4181"
